const	data: [
		{
			"id": 31,
			"type": 0,
			"first_name": "Geneva",
			"last_name": "Moen",
			"email": "test@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "8987858598",
			"address": "MP Nagar, Bhopal",
			"city": "Bhopal",
			"postal_code": "462002",
			"country": "India",
			"state": "MP",
			"is_default": 0
		},
		{
			"id": 34,
			"type": 0,
			"first_name": "Geneva",
			"last_name": "Moen",
			"email": "test@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "8987858598",
			"address": "MP Nagar, Bhopal",
			"city": "Bhopal",
			"postal_code": "462002",
			"country": "India",
			"state": "MP",
			"is_default": 0
		},
		{
			"id": 35,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 36,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 37,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 38,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 39,
			"type": 2,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 40,
			"type": 1,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 41,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		},
		{
			"id": 42,
			"type": 0,
			"first_name": "YYYY",
			"last_name": "zzzzzz",
			"email": "xxyy@test.com",
			"country_code": "IN",
			"phone_code": "+91",
			"mobile_number": "5678765787",
			"address": "MP nagar, RPA",
			"city": "Bhopal",
			"postal_code": "4652220",
			"country": "India",
			"state": "MP",
			"is_default": 1
		}
	];

// need to manupulated data by below format

const result = data.address.reduce((acc, data) => {
            let type = data.type == 1 ? "Shipping" : data.type == 2 ? "Billing" : "Other"
            acc[type] = acc[type] || [];
            acc[type].push(data);
            return acc;
          }, Object.create(null));
        });

//result data below
	"Other": [
			{
				"id": 31,
				"type": 0,
				"first_name": "Geneva",
				"last_name": "Moen",
				"email": "test@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "8987858598",
				"address": "MP Nagar, Bhopal",
				"city": "Bhopal",
				"postal_code": "462002",
				"country": "India",
				"state": "MP",
				"is_default": 0
			},
			{
				"id": 34,
				"type": 0,
				"first_name": "Geneva",
				"last_name": "Moen",
				"email": "test@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "8987858598",
				"address": "MP Nagar, Bhopal",
				"city": "Bhopal",
				"postal_code": "462002",
				"country": "India",
				"state": "MP",
				"is_default": 0
			},
			{
				"id": 35,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			},
			{
				"id": 36,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			},
			{
				"id": 37,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			},
			{
				"id": 38,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			},
			{
				"id": 41,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			},
			{
				"id": 42,
				"type": 0,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			}
		],
		"Billing": [
			{
				"id": 39,
				"type": 2,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			}
		],
		"Shipping": [
			{
				"id": 40,
				"type": 1,
				"first_name": "YYYY",
				"last_name": "zzzzzz",
				"email": "xxyy@test.com",
				"country_code": "IN",
				"phone_code": "+91",
				"mobile_number": "5678765787",
				"address": "MP nagar, RPA",
				"city": "Bhopal",
				"postal_code": "4652220",
				"country": "India",
				"state": "MP",
				"is_default": 1
			}
		]
	}
  
  
